version: '3'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Pictures
      MYSQL_USER: mbit
      MYSQL_PASSWORD: mbit
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    ports:
      - 80:80
    volumes:
      - app_data:/app/images
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: Pictures
      DB_USER: mbit
      DB_PASSWORD: mbit

volumes:
  db_data:
  app_data:
