version: '3.1'

services:
   db:
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: mbit
      MYSQL_PASSWORD: mbit
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database:/var/lib/mysql